### ISSUE TITLE
Fessインストールガイドのインストールの章について

### ISSUE THREAD

**Issue by HidekazuMorimoto** [codelibs/fess-docs#42]
UbuntuにてFessインストールガイド（http://fess.codelibs.org/ja/11.4/install/index.html）
を参照しながらインストールを実施していたのですが、
インストールの章に「ZIP パッケージの場合」と「RPM パッケージの場合」の節はあるのですが、 
DEBパッケージ場合のコマンドラインの実行例の案内がないので戸惑いました。
「DEBパッケージの場合」をくわえて実行例を追記すればubuntuユーザにも理解しやすいのではないでしょうか。

**Comment by marevol** [comment]
ありがとうございます。
プルリクをいただければマージさせていただきます。
